targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: duniter_indexer|lib/graphql/schema/duniter-indexer.schema.graphql
          type_overrides:
            jsonb:
              name: JsonObject
              import: "package:built_value/json_object.dart"
            numeric:
              name: int
              import: "dart:core"
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: duniter_indexer|lib/graphql/schema/duniter-indexer.schema.graphql
          type_overrides:
            jsonb:
              name: JsonObject
              import: "package:built_value/json_object.dart"
            numeric:
              name: int
              import: "dart:core"
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer
