// Mocks generated by Mockito 5.4.6 from annotations
// in ginkgo/test/ui/widgets/fourth_screen/transactions_list/transactions_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:ginkgo/data/models/app_cubit.dart' as _i6;
import 'package:ginkgo/data/models/app_state.dart' as _i2;
import 'package:ginkgo/data/models/multi_wallet_transaction_cubit.dart' as _i12;
import 'package:ginkgo/data/models/multi_wallet_transaction_state.dart' as _i3;
import 'package:ginkgo/data/models/node_list_cubit.dart' as _i14;
import 'package:ginkgo/data/models/transaction.dart' as _i13;
import 'package:ginkgo/data/models/transaction_state.dart' as _i4;
import 'package:ginkgo/data/models/utxo.dart' as _i16;
import 'package:ginkgo/data/models/utxo_cubit.dart' as _i15;
import 'package:ginkgo/data/models/utxo_state.dart' as _i5;
import 'package:ginkgo/g1/currency.dart' as _i8;
import 'package:ginkgo/g1/distance_precompute.dart' as _i10;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppState_0 extends _i1.SmartFake implements _i2.AppState {
  _FakeAppState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiWalletTransactionState_1 extends _i1.SmartFake
    implements _i3.MultiWalletTransactionState {
  _FakeMultiWalletTransactionState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionState_2 extends _i1.SmartFake
    implements _i4.TransactionState {
  _FakeTransactionState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUtxoState_3 extends _i1.SmartFake implements _i5.UtxoState {
  _FakeUtxoState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppCubit extends _i1.Mock implements _i6.AppCubit {
  MockAppCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get storagePrefix => (super.noSuchMethod(
        Invocation.getter(#storagePrefix),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storagePrefix),
        ),
      ) as String);

  @override
  bool get isIntroViewed => (super.noSuchMethod(
        Invocation.getter(#isIntroViewed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWalletCreatedViewed => (super.noSuchMethod(
        Invocation.getter(#isWalletCreatedViewed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWarningViewed => (super.noSuchMethod(
        Invocation.getter(#isWarningViewed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWarningBrowserViewed => (super.noSuchMethod(
        Invocation.getter(#isWarningBrowserViewed),
        returnValue: false,
      ) as bool);

  @override
  bool get isExpertMode => (super.noSuchMethod(
        Invocation.getter(#isExpertMode),
        returnValue: false,
      ) as bool);

  @override
  _i8.Currency get currency => (super.noSuchMethod(
        Invocation.getter(#currency),
        returnValue: _i8.Currency.G1,
      ) as _i8.Currency);

  @override
  double get currentUd => (super.noSuchMethod(
        Invocation.getter(#currentUd),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasRecentExport => (super.noSuchMethod(
        Invocation.getter(#hasRecentExport),
        returnValue: false,
      ) as bool);

  @override
  int get recentExportReminderInDays => (super.noSuchMethod(
        Invocation.getter(#recentExportReminderInDays),
        returnValue: 0,
      ) as int);

  @override
  bool get isV2 => (super.noSuchMethod(
        Invocation.getter(#isV2),
        returnValue: false,
      ) as bool);

  @override
  _i2.AppState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAppState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AppState);

  @override
  _i9.Stream<_i2.AppState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i2.AppState>.empty(),
      ) as _i9.Stream<_i2.AppState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get storageToken => (super.noSuchMethod(
        Invocation.getter(#storageToken),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storageToken),
        ),
      ) as String);

  @override
  void introViewed() => super.noSuchMethod(
        Invocation.method(
          #introViewed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void walletCreatedViewed() => super.noSuchMethod(
        Invocation.method(
          #walletCreatedViewed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warningViewed() => super.noSuchMethod(
        Invocation.method(
          #warningViewed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warningBrowserViewed() => super.noSuchMethod(
        Invocation.method(
          #warningBrowserViewed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AppState fromJson(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeAppState_0(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i2.AppState);

  @override
  Map<String, dynamic> toJson(_i2.AppState? state) => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [state],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void setExpertMode(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setExpertMode,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool onFinishTutorial(String? tutorialId) => (super.noSuchMethod(
        Invocation.method(
          #onFinishTutorial,
          [tutorialId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool wasTutorialShown(String? tutorialId) => (super.noSuchMethod(
        Invocation.method(
          #wasTutorialShown,
          [tutorialId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setG1Currency() => super.noSuchMethod(
        Invocation.method(
          #setG1Currency,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDUCurrency() => super.noSuchMethod(
        Invocation.method(
          #setDUCurrency,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUd(double? currentUd) => super.noSuchMethod(
        Invocation.method(
          #setUd,
          [currentUd],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool shouldUpdateUd() => (super.noSuchMethod(
        Invocation.method(
          #shouldUpdateUd,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setV2Mode(bool? v2mode) => super.noSuchMethod(
        Invocation.method(
          #setV2Mode,
          [v2mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDistancePreCompute(_i10.DistancePrecompute? distancePrecompute) =>
      super.noSuchMethod(
        Invocation.method(
          #setDistancePreCompute,
          [distancePrecompute],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHasRecentExport(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setHasRecentExport,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRecentExportReminderInDays(int? days) => super.noSuchMethod(
        Invocation.method(
          #setRecentExportReminderInDays,
          [days],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.AppState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i2.AppState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void hydrate({
    _i11.Storage? storage,
    _i11.OnHydrationError? onError = _i11.defaultOnHydrationError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #hydrate,
          [],
          {
            #storage: storage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [MultiWalletTransactionCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiWalletTransactionCubit extends _i1.Mock
    implements _i12.MultiWalletTransactionCubit {
  MockMultiWalletTransactionCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get storagePrefix => (super.noSuchMethod(
        Invocation.getter(#storagePrefix),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storagePrefix),
        ),
      ) as String);

  @override
  _i3.MultiWalletTransactionState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMultiWalletTransactionState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.MultiWalletTransactionState);

  @override
  _i9.Stream<_i3.MultiWalletTransactionState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i3.MultiWalletTransactionState>.empty(),
      ) as _i9.Stream<_i3.MultiWalletTransactionState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get storageToken => (super.noSuchMethod(
        Invocation.getter(#storageToken),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storageToken),
        ),
      ) as String);

  @override
  _i3.MultiWalletTransactionState fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeMultiWalletTransactionState_1(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i3.MultiWalletTransactionState);

  @override
  Map<String, dynamic> toJson(_i3.MultiWalletTransactionState? state) =>
      (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [state],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void addPendingTransaction(
    _i13.Transaction? pendingTransaction, {
    String? key,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addPendingTransaction,
          [pendingTransaction],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> closeCubit() => (super.noSuchMethod(
        Invocation.method(
          #closeCubit,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void removePendingTransaction(
    _i13.Transaction? pendingTransaction, {
    String? key,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removePendingTransaction,
          [pendingTransaction],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePendingTransaction(
    _i13.Transaction? tx, {
    String? key,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePendingTransaction,
          [tx],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertPendingTransaction(
    _i13.Transaction? tx, {
    String? key,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #insertPendingTransaction,
          [tx],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i13.Transaction> transactions(String? pubKey) => (super.noSuchMethod(
        Invocation.method(
          #transactions,
          [pubKey],
        ),
        returnValue: <_i13.Transaction>[],
      ) as List<_i13.Transaction>);

  @override
  _i4.TransactionState currentWalletState(String? pubKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentWalletState,
          [pubKey],
        ),
        returnValue: _FakeTransactionState_2(
          this,
          Invocation.method(
            #currentWalletState,
            [pubKey],
          ),
        ),
      ) as _i4.TransactionState);

  @override
  double balance([String? pubKey]) => (super.noSuchMethod(
        Invocation.method(
          #balance,
          [pubKey],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i9.Future<List<_i13.Transaction>> fetchTransactions({
    int? retries = 5,
    int? pageSize,
    String? cursor,
    String? pubKey,
    bool? debug = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTransactions,
          [],
          {
            #retries: retries,
            #pageSize: pageSize,
            #cursor: cursor,
            #pubKey: pubKey,
            #debug: debug,
          },
        ),
        returnValue:
            _i9.Future<List<_i13.Transaction>>.value(<_i13.Transaction>[]),
      ) as _i9.Future<List<_i13.Transaction>>);

  @override
  void resetCurrentGvaNode(
    _i4.TransactionState? newState,
    _i14.NodeListCubit? cubit,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resetCurrentGvaNode,
          [
            newState,
            cubit,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> clearState() => (super.noSuchMethod(
        Invocation.method(
          #clearState,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void removeStateForKey(String? pubKey) => super.noSuchMethod(
        Invocation.method(
          #removeStateForKey,
          [pubKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void autoCleanState({
    int? maxTxPerWallet = 10,
    Duration? maxTxAge = const Duration(days: 20),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #autoCleanState,
          [],
          {
            #maxTxPerWallet: maxTxPerWallet,
            #maxTxAge: maxTxAge,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void printStateStats([bool? debug = false]) => super.noSuchMethod(
        Invocation.method(
          #printStateStats,
          [debug],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.MultiWalletTransactionState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i3.MultiWalletTransactionState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hydrate({
    _i11.Storage? storage,
    _i11.OnHydrationError? onError = _i11.defaultOnHydrationError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #hydrate,
          [],
          {
            #storage: storage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [UtxoCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUtxoCubit extends _i1.Mock implements _i15.UtxoCubit {
  MockUtxoCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get storagePrefix => (super.noSuchMethod(
        Invocation.getter(#storagePrefix),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storagePrefix),
        ),
      ) as String);

  @override
  _i5.UtxoState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUtxoState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.UtxoState);

  @override
  _i9.Stream<_i5.UtxoState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i5.UtxoState>.empty(),
      ) as _i9.Stream<_i5.UtxoState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get storageToken => (super.noSuchMethod(
        Invocation.getter(#storageToken),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storageToken),
        ),
      ) as String);

  @override
  _i5.UtxoState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(
        #fromJson,
        [json],
      )) as _i5.UtxoState?);

  @override
  Map<String, dynamic>? toJson(_i5.UtxoState? state) =>
      (super.noSuchMethod(Invocation.method(
        #toJson,
        [state],
      )) as Map<String, dynamic>?);

  @override
  _i9.Future<void> fetchUtxos(String? myPubKey) => (super.noSuchMethod(
        Invocation.method(
          #fetchUtxos,
          [myPubKey],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  List<_i16.Utxo>? consume(double? amount) =>
      (super.noSuchMethod(Invocation.method(
        #consume,
        [amount],
      )) as List<_i16.Utxo>?);

  @override
  void resetConsumedUtxos() => super.noSuchMethod(
        Invocation.method(
          #resetConsumedUtxos,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addUtxos(List<_i16.Utxo>? newUtxos) => super.noSuchMethod(
        Invocation.method(
          #addUtxos,
          [newUtxos],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.UtxoState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i5.UtxoState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void hydrate({
    _i11.Storage? storage,
    _i11.OnHydrationError? onError = _i11.defaultOnHydrationError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #hydrate,
          [],
          {
            #storage: storage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
