// Mocks generated by Mockito 5.4.6 from annotations
// in ginkgo/test/ui/widgets/fourth_screen/transactions_list/transactions_list_header_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ginkgo/data/models/utxo.dart' as _i6;
import 'package:ginkgo/data/models/utxo_cubit.dart' as _i3;
import 'package:ginkgo/data/models/utxo_state.dart' as _i2;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUtxoState_0 extends _i1.SmartFake implements _i2.UtxoState {
  _FakeUtxoState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UtxoCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUtxoCubit extends _i1.Mock implements _i3.UtxoCubit {
  MockUtxoCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get storagePrefix => (super.noSuchMethod(
        Invocation.getter(#storagePrefix),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#storagePrefix),
        ),
      ) as String);

  @override
  _i2.UtxoState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUtxoState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.UtxoState);

  @override
  _i5.Stream<_i2.UtxoState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.UtxoState>.empty(),
      ) as _i5.Stream<_i2.UtxoState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get storageToken => (super.noSuchMethod(
        Invocation.getter(#storageToken),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#storageToken),
        ),
      ) as String);

  @override
  _i2.UtxoState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(
        #fromJson,
        [json],
      )) as _i2.UtxoState?);

  @override
  Map<String, dynamic>? toJson(_i2.UtxoState? state) =>
      (super.noSuchMethod(Invocation.method(
        #toJson,
        [state],
      )) as Map<String, dynamic>?);

  @override
  _i5.Future<void> fetchUtxos(String? myPubKey) => (super.noSuchMethod(
        Invocation.method(
          #fetchUtxos,
          [myPubKey],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i6.Utxo>? consume(double? amount) =>
      (super.noSuchMethod(Invocation.method(
        #consume,
        [amount],
      )) as List<_i6.Utxo>?);

  @override
  void resetConsumedUtxos() => super.noSuchMethod(
        Invocation.method(
          #resetConsumedUtxos,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addUtxos(List<_i6.Utxo>? newUtxos) => super.noSuchMethod(
        Invocation.method(
          #addUtxos,
          [newUtxos],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.UtxoState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i2.UtxoState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void hydrate({
    _i7.Storage? storage,
    _i7.OnHydrationError? onError = _i7.defaultOnHydrationError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #hydrate,
          [],
          {
            #storage: storage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
