import 'package:flutter/material.dart';

/// Represents a decrypted NIP-44 encrypted direct message (kind 4).
@immutable
class NostrMessage {
  const NostrMessage({
    required this.id,
    required this.senderHex,
    required this.recipientHex,
    required this.content,
    required this.createdAt,
    this.pending = false,
    this.tags = const <List<String>>[],
  });

  final String id;
  final String senderHex;
  final String recipientHex;
  final String content;
  final int createdAt; // unix timestamp (seconds)
  final bool pending;  // optimistic UI: sent but not yet confirmed by relay

  /// Raw NOSTR tags. Used in self-DM channels (BRO) where sender == recipient
  /// == myHexPubkey on both sides: the tag `["client","bro"]` (BRO_ORIGIN_TAG,
  /// see Astroport.ONE/IA/bro/nostr.py::send_dm_to_owner) is the only way to
  /// tell a bot reply from a message the user actually typed — [isFromMe]'s
  /// pubkey comparison can't distinguish them in that case.
  final List<List<String>> tags;

  DateTime get dateTime =>
      DateTime.fromMillisecondsSinceEpoch(createdAt * 1000);

  bool isFromMe(String myHexPubkey) => senderHex == myHexPubkey;

  /// True if this event carries BRO_ORIGIN_TAG (`["client","bro"]`) — a
  /// self-DM reply generated by the BRO daemon, not typed by the user.
  bool get isBotReply =>
      tags.any((List<String> t) => t.length >= 2 && t[0] == 'client' && t[1] == 'bro');

  /// Returns the OTHER party's hexPubkey relative to [myHex].
  String peerHex(String myHex) =>
      senderHex == myHex ? recipientHex : senderHex;

  NostrMessage copyWith({bool? pending}) => NostrMessage(
        id: id,
        senderHex: senderHex,
        recipientHex: recipientHex,
        content: content,
        createdAt: createdAt,
        pending: pending ?? this.pending,
        tags: tags,
      );

  @override
  bool operator ==(Object other) =>
      other is NostrMessage && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

/// Represents a single conversation with a peer.
@immutable
class NostrConversation {
  const NostrConversation({
    required this.peerHex,
    required this.lastMessage,
    this.peerName,
    this.peerPicture,
    this.unreadCount = 0,
  });

  final String peerHex;
  final NostrMessage lastMessage;
  final String? peerName;
  final String? peerPicture;
  final int unreadCount;

  NostrConversation copyWith({
    String? peerName,
    String? peerPicture,
    int? unreadCount,
    NostrMessage? lastMessage,
  }) {
    return NostrConversation(
      peerHex: peerHex,
      lastMessage: lastMessage ?? this.lastMessage,
      peerName: peerName ?? this.peerName,
      peerPicture: peerPicture ?? this.peerPicture,
      unreadCount: unreadCount ?? this.unreadCount,
    );
  }
}
